<?php

namespace App\Nova\Filters\ActionEvent;

use App\Models\ActionEvent;
use App\Models\User;
use Laravel\Nova\Fields\Filters\MultiSelectFilter;
use Laravel\Nova\Filters\Filter;
use Laravel\Nova\Http\Requests\NovaRequest;
use Outl1ne\NovaInputFilter\InputFilter;


class InitiatedBy extends MultiSelectFilter
{

    /**
     * Apply the filter to the given query.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply($request, $query, $value)
    {
        return $query->whereIn('user_id',$value);
    }

    public function options(NovaRequest $request)
    {
        $user_ids = ActionEvent::query()->groupBy('user_id')->get('user_id')->pluck('user_id')->toArray();
        return User::query()->find($user_ids,['name','id'])->pluck('name','id')->toArray(); // TODO: Change the autogenerated stub
    }

}
